/**
 * Amplify build helper for WMW SSR.
 *
 * Next.js 16 keeps `process.env.WMW_*` as runtime lookups, and Amplify only
 * deploys `.next/**`, so `.env.production` never reaches Server Actions.
 *
 * This script writes non-secret config into `src/lib/wmw/wmw-ssr-config.ts`
 * (bundled into `.next/server`). The Google SA JSON stays in Amplify Hosting
 * Secrets / SSM and is read at runtime via the SSR Compute IAM role.
 */
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export const WMW_SSR_CONFIG_PATH = 'src/lib/wmw/wmw-ssr-config.ts';

export const DEFAULT_WMW_GOOGLE_SA_SECRET_NAME = 'wmw.google-service-account';
export const DEFAULT_WMW_AMPLIFY_APP_ID = 'd3j7dgxx3prj17';
export const DEFAULT_WMW_AWS_REGION = 'eu-west-2';

export type WmwSsrConfigValues = {
  appId: string;
  region: string;
  spreadsheetId: string | null;
  googleSaSecretName: string;
};

export type WriteWmwSsrConfigResult = {
  path: string;
  spreadsheetIdSet: boolean;
};

export function resolveWmwSsrConfigValues(
  env: Record<string, string | undefined> = process.env,
): WmwSsrConfigValues {
  const spreadsheetId = env.WMW_SPREADSHEET_ID?.trim() || null;
  const googleSaSecretName =
    env.WMW_GOOGLE_SA_SECRET_NAME?.trim() || DEFAULT_WMW_GOOGLE_SA_SECRET_NAME;
  const appId = env.AWS_APP_ID?.trim() || DEFAULT_WMW_AMPLIFY_APP_ID;
  const region =
    env.AWS_REGION?.trim() ||
    env.AWS_DEFAULT_REGION?.trim() ||
    DEFAULT_WMW_AWS_REGION;

  return { appId, region, spreadsheetId, googleSaSecretName };
}

/** Build the TypeScript module source (safe string escaping via JSON.stringify). */
export function buildWmwSsrConfigModuleSource(
  values: WmwSsrConfigValues,
): string {
  return `/**
 * Non-secret WMW SSR config available to Server Actions.
 * Generated by scripts/write-amplify-ssr-env.ts during Amplify build.
 * Google SA JSON is fetched at runtime from SSM (compute role) — not stored here.
 */
import 'server-only';

export type WmwSsrConfig = {
  /** Amplify app id (SSM path prefix). */
  appId: string;
  /** AWS region for SSM. */
  region: string;
  /** Equity Workbook spreadsheet ID (non-secret). */
  spreadsheetId: string | null;
  /** Hosting secret leaf name under /amplify/shared/{appId}/. */
  googleSaSecretName: string;
};

export const wmwSsrConfig: WmwSsrConfig = {
  appId: ${JSON.stringify(values.appId)},
  region: ${JSON.stringify(values.region)},
  spreadsheetId: ${JSON.stringify(values.spreadsheetId)},
  googleSaSecretName: ${JSON.stringify(values.googleSaSecretName)},
};
`;
}

export function writeWmwSsrConfigFile(
  env: Record<string, string | undefined> = process.env,
  filePath = WMW_SSR_CONFIG_PATH,
): WriteWmwSsrConfigResult {
  const values = resolveWmwSsrConfigValues(env);
  writeFileSync(filePath, buildWmwSsrConfigModuleSource(values), 'utf8');

  if (values.spreadsheetId) {
    console.log(
      `write-amplify-ssr-env: wrote ${filePath} (spreadsheetId set, SA via runtime SSM)`,
    );
  } else {
    console.log(
      `write-amplify-ssr-env: wrote ${filePath} (WARNING: WMW_SPREADSHEET_ID missing)`,
    );
  }

  return { path: filePath, spreadsheetIdSet: Boolean(values.spreadsheetId) };
}

/** @deprecated Prefer writeWmwSsrConfigFile — kept as amplify.yml entrypoint name. */
export function writeAmplifySsrEnvFile(
  env: Record<string, string | undefined> = process.env,
): WriteWmwSsrConfigResult {
  return writeWmwSsrConfigFile(env);
}

const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  writeWmwSsrConfigFile();
}
